import Head from "next/head";
import { Geist, Geist_Mono, Maiden_Orange } from "next/font/google";
import styles from "src/styles/Home.module.css";
import { Footer } from "src/components/Footer/Footer";
import { Main } from "src/components/Main/Main";
import { Header } from "src/components/Header/Header";

// #8 相対パスから絶対パスへの変更 設定よりユーザーは全体、ワークスペースは今のやつのみ

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Header />

        <Main page="index" />

        <Footer />
      </div>
    </>
  );
}
